FROM perl:5.28

WORKDIR /app

RUN perl -M'CPAN' -e 'my $c = "CPAN::HandleConfig"; $c->load(doit => 1, autoconfig => 1); $c->edit(prerequisites_policy => "follow"); $c->edit(build_requires_install_policy => "yes"); $c->commit' && \
	perl -M'CPAN' -e 'install DBD::mysql' &&\
	perl -M'CPAN' -e 'install HTTP::Server::Simple::CGI'
	
CMD ["perl","main.pl"]