version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.req
    hostname: "perl_server"
    volumes: 
      - './req:/app'
    ports:
      - '48080:80'
    environment: 
      - MYSQLUSER=user
      - MYSQLPASSWORD=password
      - MYSQLDB=shellmag
      - MYSQLTABLE=opinion
    depends_on: 
      - "mysql"
  
  mysql:
    image: mysql:5.7
    hostname: "linux_mysql"
    volumes:
      - "./initdb:/docker-entrypoint-initdb.d"
      #  - "./srv/mysql/db_data/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: password2018
    expose:
      - "3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci